const SPELL_TYPES = [
	{
		id: 1,
		name: 'Fireball',
		targetType: 'single',
		damageType: 'magic',
		manaCost: 2,
		cooldown: 1.0,
		duration: 1,
		damage: 25,
	},
	{
		id: 2,
		name: 'Frostshard',
		targetType: 'single',
		damageType: 'magic',
		manaCost: 2,
		cooldown: 1.0,
		duration: 1,
		damage: 25,
	},
	{
		id: 3,
		name: 'lightning bolt',
		targetType: 'single',
		damageType: 'magic',
		manaCost: 2,
		cooldown: 1.0,
		duration: 1,
		damage: 25,
	},
	{
		id: 4,
		name: 'Earth throw',
		targetType: 'single',
		damageType: 'magic',
		manaCost: 2,
		cooldown: 1.0,
		duration: 1,
		damage: 25,
	},
	{
		id: 5,
		name: 'Stab',
		targetType: 'single',
		damageType: 'physical',
		manaCost: 2,
		cooldown: 1.0,
		duration: 1,
		damage: 25,
	},
	{
		id: 6,
		name: 'Exura Gran',
		targetType: 'single',
		damageType: 'heal',
		manaCost: 3,
		cooldown: 5.0,
		damage: 25,
	},
];

export default SPELL_TYPES;
