const SPELL_TYPES = [
	{
		id: 1,
		name: 'Fireball',
		targetType: 'single',
		damageType: 'magic',
		manaCost: 2,
		cooldown: 1.0,
		duration: 1,
		damage: 5,
	},
	// {
	// 	id: 2,
	// 	name: 'Frost Nova',
	// 	targetType: 'aoe',
	// 	damageType: 'magic',
	// 	manaCost: 3,
	// 	cooldown: 3.0,
	// 	duration: 1,
	// 	damage: 15,
	// },
	// {
	// 	id: 3,
	// 	name: 'Poison Cloud',
	// 	targetType: 'aoe',
	// 	damageType: 'magic',
	// 	manaCost: 2,
	// 	cooldown: 2.0,
	// 	duration: 2,
	// 	damage: 10,
	// },
	{
		id: 4,
		name: 'Stab',
		targetType: 'single',
		damageType: 'physical',
		manaCost: 2,
		cooldown: 1.0,
		duration: 1,
		damage: 5,
	},
	{
		id: 5,
		name: 'Exura Gran',
		targetType: 'single',
		damageType: 'heal',
		manaCost: 3,
		cooldown: 5.0,
		damage: 25,
	},
];

export default SPELL_TYPES;
