// TODO: moved isCompleted back to state, and just keep an array of completed IDs.

const ZONE_TYPES = [
	{
		title: 'Zone 1 - The Eternal Blaze',
		zone: 1,
		isCompleted: true,
		isLocked: false,
		stages: [
			{
				stage: 1,
				title: 'Stage 1 - Fire Caverns',
				isCompleted: true,
				isLocked: false,
				minMonsters: 2,
				maxMonsters: 4,
				monsters: [9, 10],
				minLevel: 1,
				maxLevel: 5,
			},
			{
				stage: 2,
				title: 'Stage 2 - Lava Path',
				isCompleted: true,
				isLocked: false,
				minMonsters: 2,
				maxMonsters: 3,
				monsters: [2],
				minLevel: 5,
				maxLevel: 10,
			},
			{
				stage: 3,
				title: 'Stage 3 - Fire Mountain',
				isCompleted: true,
				isLocked: false,
				minMonsters: 1,
				maxMonsters: 1,
				monsters: [3],
				minLevel: 10,
				maxLevel: 15,
			},
		],
	},
	{
		title: 'Zone 2 - Ice Caverns of Doom',
		zone: 2,
		isCompleted: false,
		isLocked: false,
		stages: [
			{
				stage: 1,
				title: 'Stage 1 - Shattered Bones',
				isCompleted: true,
				isLocked: false,
				minMonsters: 3,
				maxMonsters: 3,
				monsters: [4],
				minLevel: 15,
				maxLevel: 20,
			},
			{
				stage: 2,
				title: 'Stage 2 - Wintery Brawl',
				isCompleted: false,
				isLocked: false,
				minMonsters: 2,
				maxMonsters: 2,
				monsters: [5],
				minLevel: 20,
				maxLevel: 25,
			},
			{
				stage: 3,
				title: 'Stage 3 - Frozen Solid',
				isCompleted: false,
				isLocked: true,
				minMonsters: 1,
				maxMonsters: 1,
				monsters: [6],
				minLevel: 25,
				maxLevel: 30,
			},
		],
	},
	{
		title: 'Zone 3 - Plagued Swamps',
		zone: 3,
		isCompleted: false,
		isLocked: true,
		stages: [
			{
				stage: 1,
				title: 'Stage 1 - Infested Marsh',
				isCompleted: false,
				isLocked: true,
				minMonsters: 1,
				maxMonsters: 1,
				monsters: [7],
				minLevel: 30,
				maxLevel: 35,
			},
			{
				stage: 2,
				title: 'Stage 2 - Snakes!',
				isCompleted: false,
				isLocked: true,
				minMonsters: 3,
				maxMonsters: 3,
				monsters: [8],
				minLevel: 35,
				maxLevel: 40,
			},
			{
				stage: 3,
				title: 'Stage 3 - Consumed from Within',
				isCompleted: false,
				isLocked: true,
				minMonsters: 5,
				maxMonsters: 5,
				monsters: [1],
				minLevel: 40,
				maxLevel: 45,
			},
		],
	},
];

export default ZONE_TYPES;
